### ISSUE TITLE
13B 解密权重问题

### ISSUE THREAD

**Issue by flaviadeutsch** [OpenBuddy/OpenBuddy#12]
问题1、13B是否通过如下命令解密？
```
python(3) decrypt.py [path-to-consolidated.00.pth] [path-to-our-model-folder]
python(3) decrypt.py [path-to-consolidated.01.pth] [path-to-our-model-folder]
```
问题2、运行解密命令后，是否 path-to-our-model-folder下的3个bin.enc文件就是解密后的权重了。
问题3、解密后的权重，能否将bin.enc 文件改成bin使用？
问题4、在解密后的权重继续微调，得到的checkpoints是解密的还是加密的？

**Comment by 44670** [comment]
1. 是的，请仔细阅读文档和相关代码，第二个参数是目录，会自动解密目录里的所有文件，所以只需只需一次。
2. 并非如此，会创建bin文件，enc文件会保留（完成解密后可以删除enc）
3. 当然是解密的。

**Comment by flaviadeutsch** [comment]
感谢您的答复，关于问题一，我就是看了文档没有弄清楚，还得麻烦您确认一下，您的13B的加密权重也是用LLaMA 7B的原版的权重中的consolidated.00.pth解密的，是这样理解的对吗？

**Comment by 44670** [comment]
是的，所有文件都是用固定的7B consolidated.00.pth加密的（实际上decrypt.py会检查这个文件的md5）
