### ISSUE TITLE
回答问题类提问的结尾通常都会接一句“如果您还有其他问题，请随时问我哦！😊”

### ISSUE THREAD

**Issue by flaviadeutsch** [OpenBuddy/OpenBuddy#13]
如题
两个问题：
1、如果您还有其他问题，请随时问我哦！这样的短语可以去除吗？
2、回答问题还经常有网络图标，笑脸什么的？这个是怎么控制的，可以去除吗？

**Comment by flaviadeutsch** [comment]
比如问：克林顿是谁

**Comment by 44670** [comment]
1. 可以试试prompt engineering。

2. 这是因为prompt里指定了多用emoji，GitHub的默认prompt不会这样。

**Comment by flaviadeutsch** [comment]
多谢，有没有prompt engineering的资料推荐给我学习一下。

**Comment by 44670** [comment]
基本上像对人类一样提出要求了，例如"Be concise and clear/Be creative"，可以参考本项目里的prompt文件

**Comment by edisonzf2020** [comment]
多谢！
您的文档提到，OpenBuddy 是一个功能强大的跨语言对话模型，提供无缝的多语言支持，包括中文、英语和其他语言。

基于 Facebook 的 LLaMA 基础模型，OpenBuddy 已经对词表进行了扩展并提升了 Token Embedding。
多语言的种类是和llama13b一致的吗？
扩充的中文词表的大小是多少？
其他语言的词表有扩充吗？

**Comment by 44670** [comment]
不是的，我们针对了多种语言进行调优。
词表的话，GitHub里有写，主要是CJK（中、日、韩）字符集里的常用字，你也可以自行载入tokenizer.json查看词表的详细内容。

**Comment by edisonzf2020** [comment]
目前的效果您是全量训练的还是lora的？
方便介绍一下训练过程吗？
