### ISSUE TITLE
原版的LLaMA-7B模型 在哪

### ISSUE THREAD

**Issue by yuanjie-ai** [OpenBuddy/OpenBuddy#14]
由于 LLaMA 的许可限制，您需要拥有原版的 LLaMA-7B 模型才能使用此模型。要解密模型权重，请先获取原版的LLaMA-7B模型（不是huggingface版本的），然后使用以下命令：

**Comment by 44670** [comment]
呃，原版的llama 7b在这里：https://ai.facebook.com/blog/large-language-model-llama-meta-ai/

需要填写下列表格申请：
https://docs.google.com/forms/d/e/1FAIpQLSfqNECQnMkycAp2jP4Z9TFX0cGR4uf7b_fBxjY_OjhJILlKGA/viewform
