### ISSUE TITLE
能否添加更多的模型使用手册，让新用户更友好呢？

### ISSUE THREAD

**Issue by skykiseki** [OpenBuddy/OpenBuddy#16]
只是提个建议，从苏神那边过来知道的，觉得openbuddy的潜力很大，但是文档之类的实在是不够丰富，新用户进来时候的体验是很不友好的，希望能优化。

补充一句：大佬们牛逼

**Comment by skykiseki** [comment]
举个例子，比如V1.5对比V1.4的差别和优势？

**Comment by 44670** [comment]
好的，我们目前的主要精力还在训练模型上面！文档的话也有完善的计划。

目前可以考虑使用Langport框架进行推理，可以参考它们的项目的文档。我们自研的推理框架还在开发后，完成后会提供相关文档。

关于不同版本的差别和优势，这个其实我们自己也不是很清楚，我们有一套内部的测试题，但是这显然只能反映模型一部分的差异，发出来会导致误导。

所以目前我们还是希望用户能够自己测试多个模型（而不是对模型版本有先入为主的印象），并体验其中的差异后分享给我们，我们在discord上开放了很多版本的频道，欢迎测试。
