### ISSUE TITLE
如何在hugginface使用

### ISSUE THREAD

**Issue by superyc** [OpenBuddy/OpenBuddy#17]
用AutoModelForCausalLM，报错：
No module named 'transformers_modules.openbuddy-falcon-7b-v1'

**Comment by 44670** [comment]
falcon模型加载时需要设置trust remote code

**Comment by dizhenx** [comment]
> falcon模型加载时需要设置trust remote code

huggingface上好像不能直接推理做问答

**Comment by 44670** [comment]
> > falcon模型加载时需要设置trust remote code
> 
> huggingface上好像不能直接推理做问答

需要prompt是User Assistant的格式，并且最好带上system.prompt

**Comment by Elenore1997** [comment]
相似的问题，我是模型下载到本地之后，使用AutoModelForCausalLM来加载：
`model = AutoModelForCausalLM.from_pretrained(
    model_path,
    trust_remote_code=True,
    device_map="auto",
    torch_dtype=torch.bfloat16,
)`
model_path是我本地的目录，提示：ModuleNotFoundError: No module named 'transformers_modules.openbuddy-falcon-7b-v1。
请问在模型文件在本地时应该如何加载呢？

**Comment by 44670** [comment]
> 相似的问题，我是模型下载到本地之后，使用AutoModelForCausalLM来加载： `model = AutoModelForCausalLM.from_pretrained( model_path, trust_remote_code=True, device_map="auto", torch_dtype=torch.bfloat16, )` model_path是我本地的目录，提示：ModuleNotFoundError: No module named 'transformers_modules.openbuddy-falcon-7b-v1。 请问在模型文件在本地时应该如何加载呢？

好像mode_patch最后要加个`/`，我再确认一下

**Comment by Elenore1997** [comment]
> > 相似的问题，我是模型下载到本地之后，使用AutoModelForCausalLM来加载： `model = AutoModelForCausalLM.from_pretrained( model_path, trust_remote_code=True, device_map="auto", torch_dtype=torch.bfloat16, )` model_path是我本地的目录，提示：ModuleNotFoundError: No module named 'transformers_modules.openbuddy-falcon-7b-v1。 请问在模型文件在本地时应该如何加载呢？
> 
> 好像mode_patch最后要加个`/`，我再确认一下

您是对的，需要在路径后面加个斜杠~谢谢所提供的模型，我再去体验下，希望加载路径的方式能够统一一下~

**Comment by 44670** [comment]
> > > 相似的问题，我是模型下载到本地之后，使用AutoModelForCausalLM来加载： `model = AutoModelForCausalLM.from_pretrained( model_path, trust_remote_code=True, device_map="auto", torch_dtype=torch.bfloat16, )` model_path是我本地的目录，提示：ModuleNotFoundError: No module named 'transformers_modules.openbuddy-falcon-7b-v1。 请问在模型文件在本地时应该如何加载呢？
> > 
> > 
> > 好像mode_patch最后要加个`/`，我再确认一下
> 
> 您是对的，需要在路径后面加个斜杠，谢谢所提供的模型，我再去体验下，希望加载路径的方式能够统一一下~

这个貌似是hf的问题，不知道为啥llama又不需要

examples目录已经更新啦~

**Comment by lvqiankun** [comment]
raise EnvironmentError(
OSError: Can't load the configuration of 'OpenBuddy/openbuddy-falcon-7b-v1.5-fp16/'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'OpenBuddy/openbuddy-falcon-7b-v1.5-fp16/' is the correct path to a directory containing a config.json file
<img width="893" alt="image" src="https://github.com/OpenBuddy/OpenBuddy/assets/14866530/83b77f2c-f3db-421a-8da6-877440c097d4">

这个问题是什么原因呢？我看了config.json是存在的

**Comment by 44670** [comment]
> raise EnvironmentError( OSError: Can't load the configuration of 'OpenBuddy/openbuddy-falcon-7b-v1.5-fp16/'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'OpenBuddy/openbuddy-falcon-7b-v1.5-fp16/' is the correct path to a directory containing a config.json file <img alt="image" width="893" src="https://user-images.githubusercontent.com/14866530/244670039-83b77f2c-f3db-421a-8da6-877440c097d4.png">
> 
> 这个问题是什么原因呢？我看了config.json是存在的。我是clone本仓库，修改了下模型地址，直接执行的hello.py

参考一下新版本的hello.py，直接用OpenBuddy/openbuddy-falcon-7b-v5-fp16，本地的话貌似要在前面加./，另外路径里面不能有小数点

**Comment by lvqiankun** [comment]
> 谢谢，更新最新的模型后可以了
