### ISSUE TITLE
falcon相关代码

### ISSUE THREAD

**Issue by jiangix-paper** [OpenBuddy/OpenBuddy#18]
您好，非常棒的工作，请问对falcon进行继续预训练或者微调的代码，会发布出来吗

**Comment by 44670** [comment]
你好，可以参考Fastchat项目的训练代码。但是，我们不太确定基于这个模型继续预训练/微调的效果如何，可能会不好。

**Comment by 44670** [comment]
> 

可以试试examples/hello.py，要修改一下，加载模型的时候要设置trust remote code参数

**Comment by jiangix-paper** [comment]
好的，感谢回复。falcon本身应该是英文的。您那边在扩充到多语的时候，是采用的多语的文本数据进行继续预训练的吗？还是采用多语的指令数据进行SFT呢？

**Comment by 44670** [comment]
> 好的，感谢回复。falcon本身应该是英文的。您那边在扩充到多语的时候，是采用的多语的文本数据进行继续预训练的吗？还是采用多语的指令数据进行SFT呢？

都需要

**Comment by jiangix-paper** [comment]
OK，了解了，谢谢

**Comment by dizhenx** [comment]
> > 
> 
> 可以试试examples/hello.py，要修改一下，加载模型的时候要设置trust remote code参数

hello.py是使用的model = LlamaForCausalLM.from_pretrained  进行加载的，不适合faclon

**Comment by 44670** [comment]
> > > 
> > 
> > 
> > 可以试试examples/hello.py，要修改一下，加载模型的时候要设置trust remote code参数
> 
> hello.py是使用的model = LlamaForCausalLM.from_pretrained 进行加载的，不适合faclon

哦哦哦，抱歉！我会尽快更新代码，你先换成AutoModelForCausalLM试试~

**Comment by 44670** [comment]
你好，代码已经更新啦

**Comment by yucc-leon** [comment]
尝试加载 Falcon 仍然提示：
ModuleNotFoundError: No module named 'transformers_modules.OpenBuddy.openbuddy-falcon-7b-v1'

我的代码：
model = AutoModelForCausalLM.from_pretrained("OpenBuddy/openbuddy-falcon-7b-v1.5-fp16", trust_remote_code=True)

请问是哪里有问题吗？

**Comment by 44670** [comment]
> 尝试加载 Falcon 仍然提示： ModuleNotFoundError: No module named 'transformers_modules.OpenBuddy.openbuddy-falcon-7b-v1'
> 
> 我的代码： model = AutoModelForCausalLM.from_pretrained("OpenBuddy/openbuddy-falcon-7b-v1.5-fp16", trust_remote_code=True)
> 
> 请问是哪里有问题吗？

可以参考下examples/hello.py，目前只能从本地目录加载，并且路径最后要有`/`

**Comment by dizhenx** [comment]
> Contributor

hello.py有问题，运行报错The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:11 for open-end generation.
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

**Comment by 44670** [comment]
> AS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

上面的warning是正常的，但是底下这个错误我还没见过，方便说一下软硬件环境吗？

**Comment by dizhenx** [comment]
> > AS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
> 
> 上面的warning是正常的，但是底下这个错误我还没见过，方便说一下软硬件环境吗？

python 3.10 torch 2.0.1 cuda 11.7  3卡部署，每张卡11g。发现加载后容易爆显存

**Comment by 44670** [comment]
> > Contributor
> 
> Input length of input_ids is 251, but `max_length` is set to 100. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`. 这个警告需要修改吗？

是的，需要改成max_new_tokens，关于显存的问题，可以试试以fp16加载，参考最新的hello.py

**Comment by edisonzf2020** [comment]
测试了您的falcon 7B的，发现基础问题的罗列不如您的llama，是因为扩充词表后的二次预训练内容不足吗？还是其他的原因？

**Comment by 44670** [comment]
> 测试了您的falcon 7B的，发现基础问题的逻辑不如您的llama，出现大量的幻觉，是因为扩充词表后的二次预训练内容不足吗？还是其他的原因？

有可能是falcon预训练阶段缺少中文领域的知识，所以在询问中国传统文化等知识方面，存在幻觉。我们测试了一下问falcon一些计算机专业的知识，表现似乎和LLaMA接近。

我们在考虑一些方案，争取下一版能改善中文知识薄弱的问题。
