### ISSUE TITLE
Huggingface使用Falcon模型错误

### ISSUE THREAD

**Issue by wwf1995** [OpenBuddy/OpenBuddy#19]
哈喽感谢你们的工作，我在使用Huggingface使用Falcon模型的时候出现了

> ModuleNotFoundError: No module named 'transformers_modules.OpenBuddy.openbuddy-falcon-7b-v1'

这个错误。

我使用的代码是

```
from transformers import AutoModel
model = AutoModel.from_pretrained("OpenBuddy/openbuddy-falcon-7b-v1.5-fp16", trust_remote_code=True)
```

请问有什么解决办法吗，如果有使用的example就更好了，非常感谢

**Comment by 44670** [comment]
AutoModelForCausalLM试试

或者你可以再等会，我们计划这两天把example目录更新一下

**Comment by dizhenx** [comment]
> AutoModelForCausalLM试试
> 
> 或者你可以再等会，我们计划这两天把example目录更新一下

discord不能用，聊天框输入文字输不进去

**Comment by 44670** [comment]
> > AutoModelForCausalLM试试
> > 或者你可以再等会，我们计划这两天把example目录更新一下
> 
> discord不能用，聊天框输入文字输不进去

需要验证邮箱才有聊天权限

**Comment by dizhenx** [comment]
> > > AutoModelForCausalLM试试
> > > 或者你可以再等会，我们计划这两天把example目录更新一下
> > 
> > 
> > discord不能用，聊天框输入文字输不进去
> 
> 需要验证邮箱才有聊天权限

已经验证了啊，都登录进去了，但是不行啊，输入文字输不进去

**Comment by 44670** [comment]
> > > > AutoModelForCausalLM试试
> > > > 或者你可以再等会，我们计划这两天把example目录更新一下
> > > 
> > > 
> > > discord不能用，聊天框输入文字输不进去
> > 
> > 
> > 需要验证邮箱才有聊天权限
> 
> 已经验证了啊，都登录进去了，但是不行啊，输入文字输不进去

那有可能是浏览器和discord不兼容，或者discord认为需要增加额外的验证，可以看看
