### ISSUE TITLE
llama.cpp not keep update to date

### ISSUE THREAD

**Issue by lucasjinreal** [OpenBuddy/OpenBuddy#2]
```
./chat-llamacpp.sh
main: build = 526 (e6a46b0)
main: seed  = 1683699286
llama.cpp: loading model from models/openbuddy-13b-v1.1-q4_0-enc/13b-q4_0.bin.enc
error loading model: unknown (magic, version) combination: 63642124, 08080001; is this really a GGML file?
llama_init_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model 'models/openbuddy-13b-v1.1-q4_0-enc/13b-q4_0.bin.enc'
main: error: unable to load model
```
hi, just wonder if the weigths keep updated to lastest llama.cpp? current unable to load it with master branch.

**Comment by 44670** [comment]
https://github.com/OpenBuddy/OpenBuddy#installation

hi, you need to decrypt it first, with the original llama file.

**Comment by lucasjinreal** [comment]
@44670 I am using 13b-q4 quantized model, does decrypt needed as well? With 7b weights?

**Comment by 44670** [comment]
yeah, all the `.enc` files should be decrypted with 7b weights

**Comment by lucasjinreal** [comment]
thanks, works like a charm!

**Comment by lucasjinreal** [comment]
@44670 wanna ask an unrelated question, didn't saw any tokenizer model file, how does buddy load token vocabulary ?

**Comment by 44670** [comment]
For ggml format, the `tokenizer.model` file is embedded into the model file.
You can find the standalone tokenizer in the bf16 repo.
