### ISSUE TITLE
[question] 扩展词表怎么实现的呀？

### ISSUE THREAD

**Issue by wangjw14** [OpenBuddy/OpenBuddy#22]
说明中提到了，OpenBuddy 的 README 中提到了，extended vocabulary, additional common characters, and enhanced token embeddings。
想问下，enhanced token embeddings 是怎么实现的呀？
扩词表后，增量预训练的数据 tokens 数量是多少呀？

**Comment by 44670** [comment]
首先需要扩充词表，具体token数量差异方面可以阅读`tokenizer.json`。

token embedding是训练得出的。
