### ISSUE TITLE
if you tried to load a pytorch model from a tf 2.0 checkpoint please set from_tf=true

### ISSUE THREAD

**Issue by WOWmoxu** [OpenBuddy/OpenBuddy#23]
我在运行python hello.py是抛出的问题
OSError: Unable to load weights from pytorch checkpoint file for 
'/openbuddy-7b-v1.3-bf16/pytorch_model-00001-of-00002.bin' at 
'/openbuddy-7b-v1.3-bf16/pytorch_model-00001-of-00002.bin'. If you tried to load a PyTorch model from a TF 2.0
checkpoint, please set from_tf=True.

transformers==4.29.1

**Comment by 44670** [comment]
是如何把.enc文件转换成.bin的？

**Comment by WOWmoxu** [comment]
> 是如何把.enc文件转换成.bin的？

**Comment by 44670** [comment]
是通过decrypt.py解密.enc文件，还是直接把enc文件改名为了bin文件？
