### ISSUE TITLE
Can the model run on multiple GPU machine

### ISSUE THREAD

**Issue by Feng-Jermey-Jierong** [OpenBuddy/OpenBuddy#25]
I have a v100 machine with a size of  4 * 16g and would like to run the  **OpenBuddy/openBuddy falcon-7b-v5-fp16** model on multiple GPUs. 

I am not sure if the mode supports running on multiple GPU machines

here is my code:
```
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device_ids = [0, 1, 2, 3] 

model_path = 'OpenBuddy/openbuddy-openllama-7b-v5-fp16'
model = AutoModelForCausalLM.from_pretrained(
    model_path, 
    device_map="auto", 
    trust_remote_code=True, 
    torch_dtype=torch.float16).to(device)
tokenizer = AutoTokenizer.from_pretrained(model_path)

model = torch.nn.DataParallel(model, device_ids=device_ids)
```
This seems incorrect

Can you answer my doubts? 

Thank you

**Comment by 44670** [comment]
For multi-gpu inference, using a inference framework is recommended, rather than rebuild the wheels.

more info: https://github.com/OpenBuddy/OpenBuddy#usage-with-inference-frameworks

**Comment by Feng-Jermey-Jierong** [comment]
I mean, I want to run this [example](https://github.com/OpenBuddy/OpenBuddy/blob/main/examples/hello.py)

but I only have one v100 machine with four 16G GPUs. 

Can I run this model on this machine

**Comment by 44670** [comment]
it might be possible,

by setting `device_map="auto", `, transformers will automatically load the model into different devices,

however, 16GB might be too small for the library working properly

**Comment by Feng-Jermey-Jierong** [comment]
You are right, the 16g is indeed a bit small. I am applying for a 32g A100 machine that can be used to run it

thanks
