### ISSUE TITLE
使用fastchat调用openbuddy-falcon-7b-v5-fp16出现乱码问题

### ISSUE THREAD

**Issue by herosunly** [OpenBuddy/OpenBuddy#26]
参照examples/hello.py修改了fastchat/model_adapter.py的内容，但是依然出现乱码问题。

![image](https://github.com/OpenBuddy/OpenBuddy/assets/24822076/a62a7bdc-fc06-459d-9164-54f28fa32fe9)

**Comment by 44670** [comment]
有可能是fastchat目前还没适配falcon的架构？可以试试在fastchat issue区看看有没有人讨论

Langport、text-generation-webui均有人试用过，可以使用falcon系列模型。
