### ISSUE TITLE
你好，我从苏神那边过来的，试了下openBuddy在外推以及2048以内的阅读理解都很优秀！请问在做指令微调的时候有什么特殊的技巧吗？

### ISSUE THREAD

**Issue by Boom-1995** [OpenBuddy/OpenBuddy#28]

**Comment by 44670** [comment]
目前还没发现确实有效的特殊技巧，不过我们的数据集组合hf上的很多种高质量的，并且是全量微调。
有可能是这两点导致结果还算可以。

**Comment by ZTTY-0111** [comment]
> 目前还没发现确实有效的特殊技巧，不过我们的数据集组合hf上的很多种高质量的，并且是全量微调。 有可能是这两点导致结果还算可以。

你好，想请教一下openbuddy sft阶段使用的数据都是指令数据吗？因为尝试下来感觉opendbuddy有很多世界知识，很好奇他是如何在sft阶段获取到这些知识的。

**Comment by 44670** [comment]
是的，大部分都是指令数据，推测知识可能是模型原本就有的，或者从指令数据学到的
