### ISSUE TITLE
weights quantized outdated

### ISSUE THREAD

**Issue by lucasjinreal** [OpenBuddy/OpenBuddy#3]
Hi, just report here, I pulled llama.cpp yesterday and got error now:

```
error loading model: this format is no longer supported (see https://github.com/ggerganov/llama.cpp/pull/1305)
```

it seems need get catch up to llama.cpp new format in bin. Will consider upgrade as possible since this changes actually 2 weeks ago.

**Comment by 44670** [comment]
Hi, 13b-v1.1-q4_0, 7b-v1.1-q4_0 has been re-coded and uploaded.
