### ISSUE TITLE
请教关于将OpenLLaMA v7版本转成ggml格式的问题

### ISSUE THREAD

**Issue by ShadowPower** [OpenBuddy/OpenBuddy#31]
非常感谢您提供基于OpenLLaMA的权重。
不过，我在将它转换成ggml格式时遇到了一些问题，似乎模型的词表大小比tokenizer.model小了一些。

错误如下：
Exception: Vocab size mismatch (model has 38464, but D:\openbuddy-openllama-13b-v7-fp16\tokenizer.model has 38656).

请问，怎样才能将其转成ggml格式，需要修改convert.py的实现吗？

**Comment by 44670** [comment]
我们完成hf模型的训练后才发现，ggml量化要求词表必须是256的倍数，所以需要扩容token embedding。

之后我们也会更新扩容后的版本，目前你可以先试试我们转好的：https://huggingface.co/OpenBuddy/openbuddy-ggml/blob/main/openbuddy-13b-v7-q4_K.bin

**Comment by 44670** [comment]
现在应当可以了。

**Comment by ShadowPower** [comment]
感谢，我下载试试

**Comment by ShadowPower** [comment]
试好了，已经没问题了
