### ISSUE TITLE
运行闪退

### ISSUE THREAD

**Issue by wangxun6** [OpenBuddy/OpenBuddy#33]
您好，我这边将模型和llama.cpp都下载安装好了。目前在windows下执行.bat程序，想问一下闪退是什么原因呢？

**Comment by 44670** [comment]
如果main.exe没有输出任何东西就闪退，可能是指令集和硬件不相符。

**Comment by wangxun6** [comment]
就是在windows平台下的，intelCPU和N卡

**Comment by 44670** [comment]
下载的文件名是什么？CPU型号？
