### ISSUE TITLE
base模型问题

### ISSUE THREAD

**Issue by Louis-y-nlp** [OpenBuddy/OpenBuddy#34]
感谢团队的工作。我看到目前放出的都是多轮对话数据sft之后的模型，有没有仅做了扩充词表的base模型，还是说扩充词表是直接在sft阶段完成的。

**Comment by Louis-y-nlp** [comment]
另外对话的 prompt 足足有238个token，想了解做这么长prompt的初衷是什么。

**Comment by 44670** [comment]
扩充词表就是在sft阶段完成的。

目前追加的token都没用上，主要是为了保证embedding 256对齐。

**Comment by Louis-y-nlp** [comment]
> 目前追加的token都没用上，主要是为了保证embedding 256对齐。
这句话不是很理解，意思是sft时候的prompt没有这么长吗？那极简的prompt格式是什么样的？可以再解释下吗？

**Comment by 44670** [comment]
哦哦，我理解错了你的问题。

如果是说system.prompt有很多个token的话，这是为了提高模型输出的稳定性，并且在用户询问模型背后原理时能介绍这个github项目。

**Comment by Louis-y-nlp** [comment]
sft的时候训练prompt也这么长吗？另外我在用flacon v6模型测试RoPE 位置插值扩充上下文的时候，发现模型在输入超长文本时推理速度特别慢，至少是其他同体量模型的五倍以上（同样的输入internLM跑完四遍了这个还没跑完一遍），但是没那么长的文本速度基本一致，请问你们有发现这个问题吗？

**Comment by 44670** [comment]
看看config.json，把use_cache改成true试试。

另外推荐text generation inference，falcon的原版实现很慢。

sft的时候的prompt比较短。

**Comment by Louis-y-nlp** [comment]
感谢🙏   可以提供一下sft的prompt吗

**Comment by Louis-y-nlp** [comment]
use_cache 默认就是 true

**Comment by 44670** [comment]
那可能就是代码的问题，建议直接用TGI。

sft的prompt是：You are a helpful assistant.
