### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by X-jun-0130** [OpenBuddy/OpenBuddy#37]
openllama模型 在tokenizer时,
如果</s>字符前不加 空格符; 无法识别,会被拆成三个token进行识别

例子:
print('openllama输出')
print(tokenizer_openllama.encode('1234.56</s>'))
print(tokenizer_openllama.encode('1234.56 </s>'))

openllama输出
[1, 31822, 31853, 31855, 31878, 31882, 31843, 31880, 31887, 1089, 31829, 31901]
[1, 31822, 31853, 31855, 31878, 31882, 31843, 31880, 31887, 2]

另外有个问题想请教下:openllama相较llama增加了6000+个词,这些词里面有没有增加中文词表,谢谢

**Comment by X-jun-0130** [comment]
结束符< /s >被github自动屏蔽掉了?  上述例子中的bug讲述的是结束符

**Comment by 44670** [comment]
openllama原本的tokenizer有问题，比如python代码里的制表符会丢失。

我们加了中文词表，但是openllama原本的问题应该救不回来了，建议用新出的llama2-13b
