### ISSUE TITLE
关于基于LLaMA2的模型的微调过程的prompt疑问

### ISSUE THREAD

**Issue by pipixia244** [OpenBuddy/OpenBuddy#38]
您好！请问openbuddy-llama2-13b这个模型在对多轮对话进行微调的时候使用的prompt是什么格式的呢？现在想对模型进行微调，但不知该用什么样的prompt，非常感谢！

**Comment by 44670** [comment]
你好，请参考我们的example和system.prompt

**Comment by pipixia244** [comment]
> 

所以您在进行多轮对话finetune时是以类似
```
You are a helpful assistant.

User: {query}
Assistant: {answer}
User: {query}
Assistant: {answer}
User: {query}
Assistant: {answer}
.....
```
这样的格式作为prompt进行训练的吗？我想要靠近您在finetune时使用的prompt格式

**Comment by 44670** [comment]
非常接近了！但是每个Assistant的回复都要加上</s>

**Comment by pipixia244** [comment]
非常感谢！

**Comment by Louis-y-nlp** [comment]
多轮对话的时候，一些训练框架比如 https://github.com/hiyouga/LLaMA-Factory/blob/main/src/llmtuner/data/template.py#L101C9-L101C9 ，用到的最终格式其实是
```
<s> You are a helpful assistant.

 User: {query}
Assistant: {answer} </s>
<s> User: {query}
Assistant: {answer} </s>
<s> User: {query}
Assistant: {answer} </s>
```

system前加bos，第0轮user前没有bos，之后每一轮对话user前加bos，Assistant的回复之后加eos，这种方式和您所用的格式是一致的吗？

**Comment by 44670** [comment]
我们没有加BOS
