### ISSUE TITLE
About python inference

### ISSUE THREAD

**Issue by lucasjinreal** [OpenBuddy/OpenBuddy#4]
Hello, am using cpp got some reasonable results, now I want inference it in python, I think you guys must have already done this since I found discord can not only reponse single message, but also mutiple users mutiple contexts, which is exactly what I need.

Here are some questions wanna ask:

1. Which python framework do u using in discord bot?
2. I found there have some Instruct prefix need to set in original llama or some other opensource models, does openbuddy need it as well? In detail it like this:
```python
self.inp_prefix = self._tokenize(self.params.instruct_inp_prefix)
        self.inp_suffix = self._tokenize(
            self.params.instruct_inp_suffix, False)
```
shall I need append these input_prefix and suffix in every single user message? If so, which suffix used? I thought it might related with data training, so am asking here, hoping for any answers.

**Comment by 44670** [comment]
Here's the English response to your issue:

Firstly, we are based on the HuggingFace Transformers library. After loading the model, you can directly call the generate method to generate responses. Please refer to this link for more information: https://github.com/OpenBuddy/OpenBuddy#usage-with-transformers-on-gpu. 

Furthermore, we do not need to set any instruction, etc. You can directly add the `User: [Insert question here]\nAssistant:` combination after the initial prompt (https://github.com/OpenBuddy/OpenBuddy/blob/main/discord.prompt) (Note that there is no space after `Assistant:`).

**Comment by 44670** [comment]
Firstly, we are based on the HuggingFace Transformers library. After loading the model, you can directly call the generate method to generate responses. Please refer to this link for more information: https://github.com/OpenBuddy/OpenBuddy#usage-with-transformers-on-gpu.

Furthermore, we do not need to set any instruction, etc. You can directly add the User: [Insert question here]\nAssistant: combination after the initial prompt (https://github.com/OpenBuddy/OpenBuddy/blob/main/discord.prompt) (Note that there is no space after Assistant:).

**Comment by lucasjinreal** [comment]
thanks, so I need insert a instruct_prefix: `User: ` and a suffix: `\nAssistant:` and finally something like this:

`User: ` + message + `\nAssistant:`

As an input, is that right?

**Comment by 44670** [comment]
Yep! just like when using it with `llama.cpp`

**Comment by lucasjinreal** [comment]
@44670 thanks, understood.
