### ISSUE TITLE
[Feature Request] Support InternLM

### ISSUE THREAD

**Issue by JimmyMa99** [OpenBuddy/OpenBuddy#40]
Dear OpenBuddy developer,

我是 InternLM 社区开发者&志愿者尖米, 大佬开源的工作对我的启发很大，希望可以探讨使用 InternLM 实现 OpenBuddy 的可能性和实现路径，我的微信是 mzm312，希望可以取得联系进行更深度的交流；

Best regards,
尖米

**Comment by 44670** [comment]
非常感谢您的建议，我们也了解到它是国内水平较高的模型之一。

目前，我们的主要精力集中在遵循FOSS协议的开源模型，以及像Llama2这样具有大规模参数并且商用许可明确的模型上。

如果InternLM未来有考虑推出遵循Apache 2.0协议或者达到千亿规模的开源模型，我们将会非常感兴趣和激动。

再次感谢您的建议，期待未来有更多的合作机会。

**Comment by JimmyMa99** [comment]
https://github.com/InternLM/InternLM/blob/main/LICENSE

![image](https://github.com/OpenBuddy/OpenBuddy/assets/101508488/407c96ad-0bb7-44e6-9d64-e112d1bb3604)


InternLM 就是 Apache 2.0 协议的吧

**Comment by 44670** [comment]
并非如此，issue里面有提到。代码是Apache2.0，但是模型是另外的协议：
https://github.com/InternLM/InternLM/issues/62#issuecomment-1632362520

这一点有一定误导性。
