### ISSUE TITLE
Training details

### ISSUE THREAD

**Issue by geronimi73** [OpenBuddy/OpenBuddy#42]
great models!

might have missed this in the repo (sorry if i I did), could you provide some more details on how you fine-tune your models, ie. full or LoRA and the structure and size of the datasets you trained on?

**Comment by 78** [comment]
OpenBuddy models are all SFT models so far.
For the recently trained models, we expanded the vocabulary with about 4000 new CJK characters and fine tuned with 1 million multilingual multi-turn conversations (40% English, 40% Chinese, 20% others)

**Comment by merlinarer** [comment]
> OpenBuddy models are all SFT models so far. For the recently trained models, we expanded the vocabulary with about 4000 new CJK characters and fine tuned with 1 million multilingual multi-turn conversations (40% English, 40% Chinese, 20% others)

How many tokens have you pretrained after expanding the vocabulary?
