### ISSUE TITLE
V100不支持 BF16 之后是否会有FP16的版本呢？

### ISSUE THREAD

**Issue by Linjiahua** [OpenBuddy/OpenBuddy#45]
valueerror: bfloat16 is only supported on gpus with compute capability of at least 8.0. your tesla v100-sxm2-32gb gpu has compute capability 7.0.

**Comment by 44670** [comment]
可以直接在cpu上转换的。

**Comment by Linjiahua** [comment]
> 

我找到了~ 谢谢哈
