### ISSUE TITLE
Doubt in Installation 

### ISSUE THREAD

**Issue by Komal-99** [OpenBuddy/OpenBuddy#50]
Hi,  I am in search of German language model which can be trained on custom dataset and can be loaded by LlamaCpp  anf langchain for question answering.

I came across your models but there is slight confusion after reading the documentation. 
![image](https://github.com/OpenBuddy/OpenBuddy/assets/74819092/7ff4864e-fc5b-49f4-ae6a-9171c7a932a5)
 
 as here mentioned, the Models page link and on that different Open Buddy models hugging face links are available. I am addressing to OpenBuddy/openbuddy-30b-ggml . Is this model trained for understanding multilingual languages or not? and it is downloadable from the repository then as per the Installation Steps do I need to Decrypt this model for German use? or load it directly using LlamaCpp to make my question answering application.

**Comment by 44670** [comment]
Hi. For llama1-based model files in `.enc` extension, you need to use `decrypt.py` to decrypt the .enc files.

Our newer, llama2-based models are recommended, and they don't need to be decrypted.

**Comment by Komal-99** [comment]
Can you share the link where I can find Llama 2 models?

**Comment by 44670** [comment]
For llama.cpp https://huggingface.co/OpenBuddy/openbuddy-gguf/tree/main

**Comment by Komal-99** [comment]
My last query is it trained for understanding german language ?

**Comment by 44670** [comment]
Our training set contains German data, however, German is a complex language and the model maybe unable to speak as a native speaker.

**Comment by Komal-99** [comment]
didn't get you to run on 2x3090s? what does that  mean also What you Suggest I should go for custom training this model on my german data or  use Langchain method to pass embeddings of my data to the model and generate answers ?

**Comment by 44670** [comment]
`2x3090s` means 2 * NVIDIA 3090 GPUs.

If you want to improve German performace of the model, you need to train the model.
