### ISSUE TITLE
34b vs 13b

### ISSUE THREAD

**Issue by Louis-y-nlp** [OpenBuddy/OpenBuddy#52]
<img width="1474" alt="截屏2023-09-19 下午3 28 58" src="https://github.com/OpenBuddy/OpenBuddy/assets/33739180/f5269716-b410-46d9-9a36-10989c731d9b">
感谢开源模型。我看Open LLM Leaderboard里34b模型分数要低于13b模型，请问34b模型的实际效果和13b对比怎样？

**Comment by 44670** [comment]
34b是基于codellama-34b，用通用对话数据训练的，模型基座可能代码能力更擅长一点。

**Comment by Louis-y-nlp** [comment]
明白了，感谢
