### ISSUE TITLE
请问openbuddy-llama2-70b-v10.1-bf16的最大token长度是多少？

### ISSUE THREAD

**Issue by HouYueJie** [OpenBuddy/OpenBuddy#53]
请问openbuddy-llama2-70b-v10.1-bf16(https://huggingface.co/OpenBuddy/openbuddy-llama2-70b-v10.1-bf16) 的最大token长度是多少?是>10K吗？
![image](https://github.com/OpenBuddy/OpenBuddy/assets/66465115/0e35120a-fc94-4354-b680-6dc32524e691)

**Comment by 44670** [comment]
模型本身是4k，可以通过NTK/rope-scaling等方法翻倍。

**Comment by HouYueJie** [comment]
@44670 非常感谢及时的回复！那后续就是继续在权重基础上，补充NTK/rope-scaling/NBCE等功能，来做长文本的扩展。
请问你们测试过10K的效果吗？我看苏神NBCE中提到能扩增50K。有做过类似的测试吗？

**Comment by 44670** [comment]
苏剑灵的测试就是在openbuddy的较小模型上完成的，可以参考下相关的代码。

**Comment by HouYueJie** [comment]
@44670 好的，十分感谢！

**Comment by HouYueJie** [comment]
@44670 我使用了苏剑林提供的测试代码，替换为70B模型。发现返回的效果不行。
![900cf0580560ae4895ae19de8aaacca](https://github.com/OpenBuddy/OpenBuddy/assets/66465115/3c7a9449-dafa-43fb-a1b9-32369df9357d)
![fe3f8230325358f0e2588e386eb74b0](https://github.com/OpenBuddy/OpenBuddy/assets/66465115/5636425f-b834-438e-8ffa-a0517d56bcf7)

**Comment by 44670** [comment]
是NBCE吗？建议追一下科学空间的博客，几个关于rope scaling的方法，这些会更好。

**Comment by HouYueJie** [comment]
是的，还试过NTK，但是效果也是一言难尽。我再试试rope scaling方法。十分感谢解惑！

**Comment by 78** [comment]
NBCE有一定的局限性，如果不考虑不同context的关联性，NBCE效果挺好。
NTK aware scaled RoPE 效果挺好的，我之前在 7B 上实验过，2 倍时不会有很明显的能力下降。
