### ISSUE TITLE
多轮对话微调为什么不沿用 Llama2 中的指令格式，发挥 Ghost attention 机制的作用？

### ISSUE THREAD

**Issue by yanyusong** [OpenBuddy/OpenBuddy#55]
Llama 2 中 chat 模版：https://github.com/facebookresearch/llama/blob/main/llama/generation.py#L284
类似：
[INST] <<SYS>>\n始终用表情回复用户。\n<</SYS>>\n\n我想去巴黎，我该干什么? [/INST]
😊
[INST] 你的心情怎么样? [/INST]
😭
[INST] 给一个旅游计划? [/INST]
 
根据[issues/38](https://github.com/OpenBuddy/OpenBuddy/issues/38) OpenBuddy 模版类似：

You are a helpful assistant.

User: {query}
Assistant: {answer}
User: {query}
Assistant: {answer}
User: {query}
Assistant: {answer}
.....

**Comment by 44670** [comment]
我们试过多种格式。目前选择的格式是在我们的数据集上效果最好的，其它的似乎更容易出现欠拟合或过拟合的问题，且在多轮对话上表现不太行。

这个格式也和目前开源界流行的Vicuna、WizardLM格式相似，可以参考一下社区里面关于这个格式的讨论。
