### ISSUE TITLE
您好！比较好奇OpenBuddy-llama3-70b的发布时间以及汉化的汉字词表设计

### ISSUE THREAD

**Issue by AlphaINF** [OpenBuddy/OpenBuddy#67]
您好！我们试用了openbuddy-llama3-8b，感觉效果非常强大
我想知道llama3-70b的多语言版本大概什么时候可以发布？
另外，llama3-8b的多语言版本中，似乎并没有发现词表有所扩大，应该只有数千个常见的汉字，请问在接下来的70b/8b版本中，是否会对此进行进一步的优化？

期待您的回复！

**Comment by 44670** [comment]
70b还在训练中，预计近期能发预览版

预览版是我们首次在70b上扩充词表的尝试，不过后续的扩词表方案还是取决于实际测试效果和社区反馈

**Comment by AlphaINF** [comment]
好的，谢谢！
期待最终的效果！
