### ISSUE TITLE
tokenizer.json to tokenizer.model

### ISSUE THREAD

**Issue by Wolfscowl** [OpenBuddy/OpenBuddy#7]
Hello, I am still quite new in the topic LLM. I am currently experimenting with your great OpenBuddy modell. But OpenBuddy uses a different tokenizer than the original LLaMA model. This is available on huggingface as a json file.

How to convert it to a model file, which is needed to convert openbuddy pytorch model to ggml?

Sorry for the stupid question,
I have already spent several hours researching on the internet and experimenting with the Transformers library.

**Comment by 44670** [comment]
Hi, I guess `tokenizer.model` is also available in the model's repo.

**Comment by Wolfscowl** [comment]
Thanks for your quick reply and for uploading the tokenizer.model :) Thank you very much.

How to create such tokenizer.model file from tokenizer.json? 
I would like to understand it, but I can't find anything about it on the Internet,

That is what I have been trying to do.

from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("tokenizer_folder")
tokenizer.save_pretrained("tokenizer_folder/output_folder")

But it create the following files:
- special_tokens_map.json
- tokenizer.json
- tokenizer_config.json

Can you explain me briefly? That would be very nice.

**Comment by 44670** [comment]
I guess only the forward process `tokenizer.model -> tokenizer.json` is possible in huggingface.

**Comment by Wolfscowl** [comment]
What framework is this model format from? 
Or with which framwork is this model format trained? 
Is the tokenizer.model based on the tokenizer.model from llama and was only trained further?

**Comment by 44670** [comment]
tokenizer.model is base on the file from the original LLaMA, in sentencepiece's format.

It is a tokenizer file including word list, not an AI model, so it doesn't need to be 'trained'.
