### ISSUE TITLE
Can't load 'openbuddy-7b-v1.1-bf16-enc' from huggingface.

### ISSUE THREAD

**Issue by Aurora-slz** [OpenBuddy/OpenBuddy#9]
We use the same loading code as in the readme file, as follows:
```python
import torch
from transformers import LlamaForCausalLM, LlamaTokenizer

model_path = './openbuddy-7b-v1.1-bf16-enc'
model = LlamaForCausalLM.from_pretrained(model_path, torch_dtype=torch.bfloat16, device_map="auto") 
tokenizer = LlamaTokenizer.from_pretrained(model_path)
```
But we get errors like `OSError: Unable to load weights from pytorch checkpoint file for 
'./openbuddy-7b-v1.1-bf16-enc/pytorch_model-00001-of-00002.bin' at 
'./openbuddy-7b-v1.1-bf16-enc/pytorch_model-00001-of-00002.bin'. If you tried to load a PyTorch model from a 
TF 2.0 checkpoint, please set from_tf=True.`

The we added 'from_tf =True' according to the error report, but still reported an error:
```python
model = LlamaForCausalLM.from_pretrained(model_path, torch_dtype=torch.bfloat16, device_map="auto", from_tf=True) 
```

```python
# error information
# anaconda3/envs/py/lib/python3.9/site-packages/transformers/modeling_utils.py:2787 in from_pretrained 

 if from_tf:
      if resolved_archive_file.endswith(".index"):  # line 2787

# AttributeError: 'list' object has no attribute 'endswith'
```
---
The version of 'transformers ' pageke is '4.30.0.dev0'.

Is there something wrong with the way loading model? Thanks!

**Comment by 44670** [comment]
Hi, you need to decrypt the model with the original LLaMA file.

https://github.com/OpenBuddy/OpenBuddy#installation
